/**
 * SKS Cloud Config  — env.js
 * ─────────────────────────────────────────────────────────
 * This file is GENERATED by GitHub Actions.
 * Do NOT commit real values.  Use GitHub Secrets.
 *
 * Local testing: fill in real values here temporarily,
 * but never push to git (env.js is in .gitignore).
 * ─────────────────────────────────────────────────────────
 */
window.SKS_CONFIG = {

  // Set to false to disable cloud and work fully offline
  CLOUD_ENABLED: true,

  // ── Cloudinary (free unsigned upload preset) ──────────────
  CLOUDINARY_CLOUD_NAME:   "dfwufilhs",       // e.g. "sks-scantech"
  CLOUDINARY_UPLOAD_PRESET:"sks_unsigned_uploads",    // unsigned preset name

  // ── Supabase (anon/public key — safe in browser) ─────────
  SUPABASE_URL:            "https://nlewnmnqytetpcrwfvlm.supabase.co",
  SUPABASE_ANON_KEY:       "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5sZXdubW5xeXRldHBjcndmdmxtIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Nzg2MzQzMDksImV4cCI6MjA5NDIxMDMwOX0.lYxVmr_6a-7BCq68UvOaiqsAs1xqGpflJZb1fgtDpJo",

  // ── EmailJS (public key — safe in browser) ───────────────
  EMAILJS_SERVICE_ID:      "service_r19w6gi",
  EMAILJS_TEMPLATE_ID:     "template_hrzjr9r",
  EMAILJS_PUBLIC_KEY:      "hSrYf7KXECv_l0BEg",

  // ── Google Sheets Apps Script Web App URL ────────────────
  GSHEET_WEBAPP_URL:       "https://script.google.com/macros/s/AKfycbwuwExSE8jXnQ-MAyIId9nrSyOxsowbOPsBegyjk9zOZ1K-4wT_vBzgzCxZUJsRaPNr8Q/exec"
};
